#!/bin/bash

# export WANDB_API_KEY="029a7cc91a821854880a156d05653e9b79d9e7d6"
export WANDB_MODE="online"

# manifest_path="/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/manifests"
manifest_path="/tmp/dicow_data/nemo_manifests"
tokenizers_path="/tmp/tokenizers"

export NUMBA_CUDA_USE_NVIDIA_BINDING="0"

# SINGLE LAYER
# python /storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/asr/av_ts_asr_transducer/speech_to_text_rnnt_bpe.py \
#     --config-path="/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/asr/conf/fastconformer/hybrid_transducer_ctc" \
#     --config-name="av_tsasr_stno_parakeet_v2_0.6b.yaml" \
#     model.train_ds.manifest_filepath=/scratch.ssd/dklement/job_13813596.pbs-m1/data/manifests/mcorec_train_trimmed_sg_nemo_manifest_dinov3_l.jsonl \
#     model.validation_ds.manifest_filepath=/scratch.ssd/dklement/job_13813596.pbs-m1/data/manifests/mcorec_dev_nemo_manifest_dinov3_l.jsonl \
#     model.tokenizer.dir=${tokenizers_path}/ls960/tokenizer_spe_bpe_v500 \
#     model.tokenizer.type="bpe" \
#     trainer.devices=-1 \
#     +evaluate_at_start=True \
#     trainer.accelerator="gpu" \
#     trainer.strategy="ddp" \
#     trainer.precision="bf16-mixed" \
#     trainer.max_epochs=1000 \
#     trainer.log_every_n_steps=10 \
#     trainer.check_val_every_n_epoch=5 \
#     +exp_manager.checkpoint_callback_params.every_n_epochs=5 \
#     model.fddt_lr_multiplier=1.0 \
#     model.optim.sched.warmup_steps=5000 \
#     model.optim.lr=0.05 \
#     model.train_ds.batch_size=2 \
#     trainer.accumulate_grad_batches=2 \
#     model.train_ds.num_workers=6 \
#     +model.train_ds.max_training_rand_seg_duration=100 \
#     +model.encoder.use_pre_pe_visual_conditioning=True \
#     +model.encoder.use_visual_conditioning_on_all_layers=True \
#     +model.encoder.visual_conditioning_method="add" \
#     +model.encoder.visual_preprocessing_model="base" \
#     +model.encoder.conditioning_embed_aggr_method="avg" \
#     +model.encoder.num_conditioning_embeds=1 \
#     +model.encoder.d_visual_embeds=1024 \
#     +model.encoder.modality_dropout_prob=0.3 \
#     model.validation_ds.num_workers=6 \
#     trainer.accumulate_grad_batches=1 \
#     model.validation_ds.batch_size=1 \
#     exp_manager.resume_if_exists=True \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/scratch.ssd/dklement/job_13813596.pbs-m1/nemo_experiments/chime9/av/test1 \
#     +init_from_ptl_ckpt=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/nemo_experiments/parakeet_v2_0.6b_nsf_test_fddt_lr_mul_100_lr0.5_dicow_data_setup_nsf_dev_longform_2k_warmup_v3/checkpoints/parakeet_v2_0.6b_nsf_test_fddt_lr_mul_100_lr0.5_dicow_data_setup_nsf_dev_longform_2k_warmup_v3--val/best.ckpt \
#     exp_manager.checkpoint_callback_params.monitor="val/cp_wer" \
#     exp_manager.create_wandb_logger=True \
#     exp_manager.wandb_logger_kwargs.name="pretrained_parakeet_v2_dcwsetup_ft_mcorec_sg_trimmed_dinov3_l_rs_100_5kwup_lr0.05_wlinear_add_pre_pe+all_layers_mdrop_0.3" \
#     exp_manager.wandb_logger_kwargs.project="dk_chime9" \
#     +init_from_pretrained="nvidia/parakeet-tdt-0.6b-v2" \
#     name="pretrained_parakeet_v2_dcwsetup_ft_mcorec_sg_trimmed_dinov3_l_rs_100_5kwup_lr0.05_wlinear_add_pre_pe+all_layers_mdrop_0.3" \
#     +model.decoding.compute_timestamps=True \
#     +model.decoding.preserve_alignments=True

# python /storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/asr/av_ts_asr_transducer/speech_to_text_rnnt_bpe.py --config-path=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/asr/conf/fastconformer/hybrid_transducer_ctc --config-name=av_tsasr_stno_parakeet_v2_0.6b.yaml model.train_ds.manifest_filepath=/scratch.ssd/dklement/job_13813596.pbs-m1/data/manifests/mcorec_train_trimmed_sg_nemo_manifest_vids.jsonl model.validation_ds.manifest_filepath=/scratch.ssd/dklement/job_13813596.pbs-m1/data/manifests/mcorec_dev_nemo_manifest_vids.jsonl model.tokenizer.dir=/tmp/tokenizers/ls960/tokenizer_spe_bpe_v500 model.tokenizer.type=bpe trainer.devices=-1 +evaluate_at_start=True trainer.accelerator=gpu trainer.strategy=ddp trainer.max_epochs=1000 trainer.log_every_n_steps=10 trainer.check_val_every_n_epoch=5 +exp_manager.checkpoint_callback_params.every_n_epochs=5 model.fddt_lr_multiplier=1.0 model.optim.sched.warmup_steps=5000 model.optim.lr=0.005 model.train_ds.batch_size=8 model.train_ds.num_workers=6 +model.train_ds.max_training_rand_seg_duration=30 +model.encoder.use_pre_pe_visual_conditioning=True +model.encoder.use_visual_conditioning_on_all_layers=True +model.encoder.visual_conditioning_method=add +model.encoder.visual_preprocessing_model=base +model.encoder.conditioning_embed_aggr_method=avg +model.encoder.num_conditioning_embeds=1 model.validation_ds.num_workers=6 trainer.accumulate_grad_batches=1 model.validation_ds.batch_size=1 exp_manager.resume_if_exists=True exp_manager.resume_ignore_no_checkpoint=True exp_manager.exp_dir=/scratch.ssd/dklement/job_13813596.pbs-m1/nemo_experiments/chime9/av/test1 +init_from_ptl_ckpt=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/nemo_experiments/parakeet_v2_0.6b_nsf_test_fddt_lr_mul_100_lr0.5_dicow_data_setup_nsf_dev_longform_2k_warmup_v3/checkpoints/parakeet_v2_0.6b_nsf_test_fddt_lr_mul_100_lr0.5_dicow_data_setup_nsf_dev_longform_2k_warmup_v3--val/best.ckpt exp_manager.checkpoint_callback_params.monitor=val/cp_wer exp_manager.create_wandb_logger=True exp_manager.wandb_logger_kwargs.name=pretrained_parakeet_v2_dcwsetup_ft_mcorec_sg_trimmed_av_rs_30_5kwup_lr0.005_wlinear_add_pre_pe+all_layers exp_manager.wandb_logger_kwargs.project=dk_chime9 +init_from_pretrained=nvidia/parakeet-tdt-0.6b-v2 name=pretrained_parakeet_v2_dcwsetup_ft_mcorec_sg_trimmed_av_rs_30_5kwup_lr0.005_wlinear_add_pre_pe+all_layers +model.decoding.compute_timestamps=True +model.decoding.preserve_alignments=True

python /storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/asr/av_ts_asr_transducer/speech_to_text_rnnt_bpe.py \
  --config-path=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/asr/conf/fastconformer/hybrid_transducer_ctc \
  --config-name=av_tsasr_stno_parakeet_v2_0.6b.yaml \
  model.train_ds.manifest_filepath=/scratch.ssd/dklement/job_13813596.pbs-m1/data/manifests/mcorec_train_trimmed_sg_nemo_manifest_vids.jsonl \
  model.validation_ds.manifest_filepath=/scratch.ssd/dklement/job_13813596.pbs-m1/data/manifests/mcorec_dev_nemo_manifest_vids.jsonl \
  model.tokenizer.dir=/tmp/tokenizers/ls960/tokenizer_spe_bpe_v500 \
  model.tokenizer.type=bpe \
  trainer.devices=-1 \
  +evaluate_at_start=True \
  trainer.accelerator=gpu \
  trainer.strategy=ddp \
  trainer.max_epochs=1000 \
  trainer.log_every_n_steps=10 \
  trainer.check_val_every_n_epoch=5 \
  +exp_manager.checkpoint_callback_params.every_n_epochs=5 \
  model.fddt_lr_multiplier=1.0 \
  model.optim.sched.warmup_steps=5000 \
  model.optim.lr=0.005 \
  model.train_ds.batch_size=16 \
  model.train_ds.num_workers=6 \
  +model.train_ds.max_training_rand_seg_duration=30 \
  +model.encoder.use_pre_pe_visual_conditioning=True \
  +model.encoder.use_visual_conditioning_on_all_layers=True \
  +model.encoder.visual_conditioning_method=add \
  +model.encoder.visual_preprocessing_model=base \
  +model.encoder.conditioning_embed_aggr_method=avg \
  +model.encoder.num_conditioning_embeds=1 \
  model.validation_ds.num_workers=6 \
  trainer.accumulate_grad_batches=1 \
  model.validation_ds.batch_size=1 \
  exp_manager.resume_if_exists=True \
  exp_manager.resume_ignore_no_checkpoint=True \
  exp_manager.exp_dir=/scratch.ssd/dklement/job_13813596.pbs-m1/nemo_experiments/chime9/av/test1 \
  +init_from_ptl_ckpt=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/nemo_experiments/parakeet_v2_0.6b_nsf_test_fddt_lr_mul_100_lr0.5_dicow_data_setup_nsf_dev_longform_2k_warmup_v3/checkpoints/parakeet_v2_0.6b_nsf_test_fddt_lr_mul_100_lr0.5_dicow_data_setup_nsf_dev_longform_2k_warmup_v3--val/best.ckpt \
  exp_manager.checkpoint_callback_params.monitor=val/cp_wer \
  exp_manager.create_wandb_logger=True \
  exp_manager.wandb_logger_kwargs.name=pretrained_parakeet_v2_dcwsetup_ft_mcorec_sg_trimmed_av_rs_30_bs16_5kwup_lr0.005_wlinear_add_pre_pe+all_layers \
  exp_manager.wandb_logger_kwargs.project=dk_chime9 \
  +init_from_pretrained=nvidia/parakeet-tdt-0.6b-v2 \
  name=pretrained_parakeet_v2_dcwsetup_ft_mcorec_sg_trimmed_av_rs_30_bs16_5kwup_lr0.005_wlinear_add_pre_pe+all_layers \
  +model.decoding.compute_timestamps=True \
  +model.decoding.preserve_alignments=True

# python /storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/asr/av_ts_asr_transducer/speech_to_text_rnnt_bpe.py \
#     --config-path="/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/asr/conf/fastconformer/hybrid_transducer_ctc" \
#     --config-name="av_tsasr_stno_parakeet_v2_0.6b.yaml" \
#     model.train_ds.manifest_filepath=/scratch.ssd/dklement/job_13813596.pbs-m1/data/manifests/mcorec_train_trimmed_sg_nemo_manifest_all_layers_vids.jsonl \
#     model.validation_ds.manifest_filepath=/scratch.ssd/dklement/job_13813596.pbs-m1/data/manifests/mcorec_dev_nemo_manifest_all_layers_vids.jsonl \
#     model.tokenizer.dir=${tokenizers_path}/ls960/tokenizer_spe_bpe_v500 \
#     model.tokenizer.type="bpe" \
#     trainer.devices=-1 \
#     +evaluate_at_start=True \
#     trainer.accelerator="gpu" \
#     trainer.strategy="ddp" \
#     trainer.precision="bf16-mixed" \
#     trainer.max_epochs=1000 \
#     trainer.log_every_n_steps=10 \
#     trainer.check_val_every_n_epoch=5 \
#     +exp_manager.checkpoint_callback_params.every_n_epochs=5 \
#     model.fddt_lr_multiplier=1.0 \
#     model.optim.sched.warmup_steps=5000 \
#     model.optim.lr=0.005 \
#     model.train_ds.batch_size=2 \
#     model.train_ds.num_workers=6 \
#     +model.train_ds.max_training_rand_seg_duration=100 \
#     +model.encoder.use_pre_pe_visual_conditioning=True \
#     +model.encoder.use_visual_conditioning_on_all_layers=True \
#     +model.encoder.visual_conditioning_method="add" \
#     +model.encoder.visual_preprocessing_model="base" \
#     +model.encoder.conditioning_embed_aggr_method="wavg" \
#     +model.encoder.num_conditioning_embeds=25 \
#     model.validation_ds.num_workers=6 \
#     trainer.accumulate_grad_batches=1 \
#     model.validation_ds.batch_size=1 \
#     exp_manager.resume_if_exists=True \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/scratch.ssd/dklement/job_13813596.pbs-m1/nemo_experiments/chime9/av/test1 \
#     +init_from_ptl_ckpt=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/nemo_experiments/parakeet_v2_0.6b_nsf_test_fddt_lr_mul_100_lr0.5_dicow_data_setup_nsf_dev_longform_2k_warmup_v3/checkpoints/parakeet_v2_0.6b_nsf_test_fddt_lr_mul_100_lr0.5_dicow_data_setup_nsf_dev_longform_2k_warmup_v3--val/best.ckpt \
#     exp_manager.checkpoint_callback_params.monitor="val/cp_wer" \
#     exp_manager.create_wandb_logger=True \
#     exp_manager.wandb_logger_kwargs.name="pretrained_parakeet_v2_dcwsetup_ft_mcorec_sg_trimmed_av_all_layers_rs_100_5kwup_lr0.005_wlinear_wavg_add_pre_pe+all_layers" \
#     exp_manager.wandb_logger_kwargs.project="dk_chime9" \
#     +init_from_pretrained="nvidia/parakeet-tdt-0.6b-v2" \
#     name="pretrained_parakeet_v2_dcwsetup_ft_mcorec_sg_trimmed_av_all_layers_rs_100_5kwup_lr0.005_wlinear_wavg_add_pre_pe+all_layers" \
#     +model.decoding.compute_timestamps=True \
#     +model.decoding.preserve_alignments=True
