#!/bin/bash

# export WANDB_API_KEY="029a7cc91a821854880a156d05653e9b79d9e7d6"
export WANDB_MODE="online"

# export NCCL_DEBUG=INFO
# export TORCH_DISTRIBUTED_DEBUG=INFO

# manifest_path="/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/manifests"
manifest_path="/tmp/dicow_data/nemo_manifests"
tokenizers_path="/tmp/tokenizers"

# python /home/jovyan/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_diar_train.py \
#     --config-path=/home/jovyan/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
#     --config-name=eend_spk_buff.yaml \
#     model.train_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_110s.jsonl \
#     model.validation_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_110s.jsonl \
#     +model.train_ds.equalize_recording_lengths=True \
#     trainer.devices=-1 \
#     trainer.accelerator=gpu \
#     trainer.strategy=ddp \
#     trainer.max_epochs=1000 \
#     trainer.log_every_n_steps=10 \
#     +trainer.check_val_every_n_epoch=10 \
#     exp_manager.checkpoint_callback_params.every_n_epochs=10 \
#     +exp_manager.checkpoint_callback_params.save_last=False \
#     model.train_ds.batch_size=64 \
#     trainer.accumulate_grad_batches=1 \
#     model.train_ds.session_len_sec=110 \
#     model.train_ds.num_workers=10 \
#     model.optim.sched.warmup_steps=2500 \
#     model.optim.sched.min_lr=1e-07 \
#     model.optim.lr=5e-5 \
#     model.sortformer_modules.dropout_rate=0.2 \
#     model.validation_ds.batch_size=4 \
#     +model.encoder.prepend_global_tokens=true \
#     +model.encoder.use_ce_spk_buffer=true \
#     model.encoder.n_layers=8 \
#     model.model_defaults.d_model=384 \
#     model.train_ds.session_len_sec=110 \
#     model.encoder.att_context_size=[128,128] \
#     model.encoder.self_attention_model=rel_pos_local_attn \
#     model.encoder.att_context_style=regular \
#     +model.encoder.global_tokens=1 \
#     +model.encoder.global_tokens_spacing=1 \
#     +model.encoder.global_attn_separate=false \
#     +evaluate_at_start=False \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/tmp/nemo_experiments/dk_nemo_eend_ami_overfit \
#     exp_manager.create_wandb_logger=True \
#     +trainer.gradient_clip_val=1.0 \
#     exp_manager.wandb_logger_kwargs.name=110s_train_110s_valid_noforcefirstactive_rel_local_attn_1_global_spk_buff_prepend_global_384d \
#     exp_manager.wandb_logger_kwargs.project=dk_nemo_eend_ami_overfit \
#     name=110s_train_110s_valid_noforcefirstactive_rel_local_attn_1_global_spk_buff_prepend_global_384d

# python /home/jovyan/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_spk_buffer_diar_train.py \
#     --config-path=/home/jovyan/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
#     --config-name=eend_spk_buff.yaml \
#     model.train_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_120s_4spks.jsonl \
#     model.validation_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_110s.jsonl \
#     +model.train_ds.equalize_recording_lengths=True \
#     trainer.devices=-1 \
#     trainer.accelerator=gpu \
#     trainer.strategy=ddp \
#     model.max_num_of_spks=4 \
#     trainer.max_epochs=1000 \
#     trainer.log_every_n_steps=10 \
#     +trainer.check_val_every_n_epoch=10 \
#     exp_manager.checkpoint_callback_params.every_n_epochs=10 \
#     +exp_manager.checkpoint_callback_params.save_last=False \
#     model.train_ds.batch_size=32 \
#     trainer.accumulate_grad_batches=1 \
#     model.train_ds.session_len_sec=120 \
#     model.train_ds.num_workers=10 \
#     model.optim.sched.warmup_steps=5000 \
#     model.optim.sched.min_lr=1e-07 \
#     model.optim.lr=3e-5 \
#     model.sortformer_modules.dropout_rate=0.2 \
#     model.validation_ds.batch_size=1 \
#     +model.encoder.prepend_global_tokens=true \
#     +model.encoder.use_ce_spk_buffer=true \
#     model.encoder.n_layers=8 \
#     model.encoder.att_context_size=[128,128] \
#     model.encoder.self_attention_model=rel_pos_local_attn \
#     model.encoder.att_context_style=regular \
#     +model.encoder.global_tokens=4 \
#     +model.encoder.global_tokens_spacing=1 \
#     +model.encoder.global_attn_separate=false \
#     +evaluate_at_start=False \
#     +init_from_nest=True \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/tmp/nemo_experiments/dk_nemo_eend_ami_overfit \
#     exp_manager.create_wandb_logger=True \
#     +trainer.gradient_clip_val=0 \
#     exp_manager.wandb_logger_kwargs.name=8l_pil_compound_lr_3e-5_warmup_5k_nogradclip_10spks_0.2_dp_local_attn_spk_buff_1_prep_global_120s_4spks \
#     exp_manager.wandb_logger_kwargs.project=dk_nemo_eend_ami_overfit \
#     name=8l_pil_compound_lr_3e-5_warmup_5k_nogradclip_10spks_0.2_dp_local_attn_spk_buff_1_prep_global_120s_4spks

# python /home/jovyan/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_spk_buffer_diar_train.py \
#     --config-path=/home/jovyan/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
#     --config-name=eend_spk_buff.yaml \
#     model.train_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_120s_4spks.jsonl \
#     model.validation_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_110s.jsonl \
#     +model.train_ds.equalize_recording_lengths=True \
#     trainer.devices=-1 \
#     trainer.accelerator=gpu \
#     trainer.strategy=ddp \
#     model.max_num_of_spks=4 \
#     trainer.max_epochs=1000 \
#     trainer.log_every_n_steps=10 \
#     +trainer.check_val_every_n_epoch=10 \
#     exp_manager.checkpoint_callback_params.every_n_epochs=10 \
#     +exp_manager.checkpoint_callback_params.save_last=False \
#     model.train_ds.batch_size=32 \
#     trainer.accumulate_grad_batches=1 \
#     model.train_ds.session_len_sec=120 \
#     model.train_ds.num_workers=10 \
#     model.optim.lr=1e-4 \
#     model.sortformer_modules.dropout_rate=0.5 \
#     model.validation_ds.batch_size=1 \
#     +model.encoder.prepend_global_tokens=true \
#     +model.encoder.use_ce_spk_buffer=true \
#     model.encoder.n_layers=4 \
#     model.model_defaults.d_model=256 \
#     model.encoder.att_context_size=[64,64] \
#     model.encoder.conv_kernel_size=1 \
#     model.encoder.self_attention_model=rel_pos_local_attn \
#     model.encoder.att_context_style=regular \
#     +model.encoder.global_tokens=4 \
#     +model.encoder.global_tokens_spacing=1 \
#     +model.encoder.global_attn_separate=false \
#     +evaluate_at_start=False \
#     +init_from_nest=False \
#     +init_conv_downsampling_from_nest=False \
#     +freeze_conv_downsampling=False \
#     +decode_only=False \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/tmp/nemo_experiments/dk_nemo_eend_ami_overfit \
#     exp_manager.create_wandb_logger=True \
#     +trainer.gradient_clip_val=5.0 \
#     exp_manager.wandb_logger_kwargs.name=4l_256d_1ks_64ctx_pil_compound_lr_1e-4_warmup_10k_5.0_gc_4spks_0.2_dp_la_sb_4_prep_global_120s \
#     exp_manager.wandb_logger_kwargs.project=dk_nemo_eend_ami_overfit \
#     name=4l_256d_1ks_64ctx_pil_compound_lr_1e-4_warmup_10k_5.0_gc_4spks_0.2_dp_la_sb_4_prep_global_120s \

# python /home/jovyan/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_spk_buffer_diar_train.py \
#     --config-path=/home/jovyan/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
#     --config-name=eend_spk_buff.yaml \
#     model.train_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_120s_4spks.jsonl \
#     model.validation_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest.jsonl \
#     +model.train_ds.equalize_recording_lengths=True \
#     trainer.devices=-1 \
#     trainer.accelerator=gpu \
#     trainer.strategy=ddp \
#     model.max_num_of_spks=4 \
#     trainer.max_epochs=1000 \
#     trainer.log_every_n_steps=10 \
#     +trainer.check_val_every_n_epoch=10 \
#     exp_manager.checkpoint_callback_params.every_n_epochs=10 \
#     +exp_manager.checkpoint_callback_params.save_last=False \
#     model.train_ds.batch_size=32 \
#     trainer.accumulate_grad_batches=1 \
#     model.train_ds.session_len_sec=120 \
#     model.train_ds.num_workers=10 \
#     model.optim.lr=3e-5 \
#     model.sortformer_modules.dropout_rate=0.5 \
#     model.validation_ds.batch_size=1 \
#     +model.encoder.prepend_global_tokens=true \
#     +model.encoder.use_ce_spk_buffer=true \
#     +model.encoder.use_ce_spk_buffer_bias=true \
#     model.encoder.n_layers=4 \
#     model.encoder.att_context_size=[64,64] \
#     model.encoder.self_attention_model=rel_pos_local_attn \
#     model.encoder.att_context_style=regular \
#     +model.encoder.global_tokens=4 \
#     +model.encoder.global_tokens_spacing=1 \
#     +model.encoder.global_attn_separate=false \
#     model.optim.sched.warmup_steps=2500 \
#     +evaluate_at_start=False \
#     +init_from_nest=True \
#     +init_conv_downsampling_from_nest=False \
#     +freeze_conv_downsampling=False \
#     +decode_only=False \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/tmp/nemo_experiments/dk_nemo_eend_ami_overfit \
#     exp_manager.create_wandb_logger=True \
#     +trainer.gradient_clip_val=5.0 \
#     exp_manager.wandb_logger_kwargs.name=4l_512d_9ks_64ctx_pil_compound_lr_3e-5_warmup_2.5k_5.0_gc_4spks_0.2_dp_la_4sb_nobias_sce_prep_global_120s \
#     exp_manager.wandb_logger_kwargs.project=dk_nemo_eend_ami_overfit \
#     name=4l_512d_9ks_64ctx_pil_compound_lr_3e-5_warmup_2.5k_5.0_gc_4spks_0.2_dp_la_4sb_nobias_sce_prep_global_120s \

python /home/jovyan/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_spk_buffer_diar_train.py \
    --config-path=/home/jovyan/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
    --config-name=eend_spk_buff.yaml \
    model.train_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/train/nemo_manifest_300s.jsonl \
    model.validation_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest.jsonl \
    +model.train_ds.equalize_recording_lengths=True \
    trainer.devices=-1 \
    trainer.accelerator=gpu \
    trainer.strategy=ddp \
    model.max_num_of_spks=10 \
    trainer.max_epochs=1000 \
    trainer.log_every_n_steps=10 \
    trainer.val_check_interval=0.5 \
    model.train_ds.batch_size=32 \
    trainer.accumulate_grad_batches=1 \
    model.train_ds.session_len_sec=300 \
    model.train_ds.num_workers=10 \
    model.optim.lr=3e-5 \
    model.sortformer_modules.dropout_rate=0.5 \
    model.validation_ds.batch_size=1 \
    +model.encoder.prepend_global_tokens=true \
    +model.encoder.use_ce_spk_buffer=true \
    +model.encoder.use_ce_spk_buffer_bias=true \
    model.encoder.n_layers=4 \
    model.encoder.att_context_size=[64,64] \
    model.encoder.self_attention_model=rel_pos_local_attn \
    model.encoder.att_context_style=regular \
    +model.encoder.global_tokens=4 \
    +model.encoder.global_tokens_spacing=1 \
    +model.encoder.global_attn_separate=false \
    model.optim.sched.warmup_steps=2500 \
    +evaluate_at_start=False \
    +init_from_nest=True \
    +init_conv_downsampling_from_nest=False \
    +freeze_conv_downsampling=False \
    +decode_only=False \
    exp_manager.resume_ignore_no_checkpoint=True \
    exp_manager.exp_dir=/tmp/nemo_experiments/dk_nemo_diar \
    exp_manager.create_wandb_logger=True \
    +trainer.gradient_clip_val=5.0 \
    exp_manager.wandb_logger_kwargs.name=4l_512d_9ks_64ctx_pil_compound_lr_3e-5_warmup_2.5k_5.0_gc_4spks_0.2_dp_la_4sb_sce_prep_global_300s \
    exp_manager.wandb_logger_kwargs.project=dk_nemo_eend_ami_overfit \
    name=4l_512d_9ks_64ctx_pil_compound_lr_3e-5_warmup_2.5k_5.0_gc_4spks_0.2_dp_la_4sb_sce_prep_global_300s \
