#!/bin/bash

# export WANDB_API_KEY="029a7cc91a821854880a156d05653e9b79d9e7d6"
export WANDB_MODE="online"

# export NCCL_DEBUG=INFO
# export TORCH_DISTRIBUTED_DEBUG=INFO

# manifest_path="/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/manifests"
manifest_path="/tmp/dicow_data/nemo_manifests"
tokenizers_path="/tmp/tokenizers"

# python /home/jovyan/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_diar_train.py \
#     --config-path=/home/jovyan/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
#     --config-name=eend_pil_loss_4spk.yaml \
#     model.train_ds.manifest_filepath=/tmp/diar_data/compound_jiangyu_dataset/data_ssd/train/nemo_manifest.json \
#     model.validation_ds.manifest_filepath=/tmp/diar_data/compound_jiangyu_dataset/data_ssd/dev/nemo_manifest_300s.jsonl \
#     +model.train_ds.equalize_recording_lengths=True \
#     trainer.devices=1 \
#     trainer.accelerator=gpu \
#     trainer.strategy=auto \
#     trainer.max_epochs=1000 \
#     trainer.log_every_n_steps=10 \
#     +trainer.check_val_every_n_epoch=1 \
#     model.train_ds.batch_size=16 \
#     trainer.accumulate_grad_batches=2 \
#     model.optim.sched.warmup_steps=2500 \
#     model.optim.sched.min_lr=1e-07 \
#     model.optim.lr=5e-5 \
#     model.sortformer_modules.dropout_rate=0.2 \
#     model.validation_ds.batch_size=16\
#     +init_from_nest=True \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/tmp/nemo_experiments \
#     exp_manager.create_wandb_logger=True \
#     +trainer.gradient_clip_val=5.0 \
#     exp_manager.wandb_logger_kwargs.name=fastconformer_eend_18l_pil_8compound_equalized_32bs_lr_5e-5_warmup_2.5k_gradclip_5_10spks_90s_nest \
#     exp_manager.wandb_logger_kwargs.project=dk_nemo_tests \
#     name=fastconformer_eend_18l_pil_8compound_equalized_32bs_lr_5e-5_warmup_2.5k_gradclip_5_10spks_90s_nest

# python /home/jovyan/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_diar_train.py \
#     --config-path=/home/jovyan/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
#     --config-name=eend_pil_loss_4spk.yaml \
#     model.train_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_110s.jsonl \
#     model.validation_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_110s.jsonl \
#     +model.train_ds.equalize_recording_lengths=True \
#     trainer.devices=-1 \
#     trainer.accelerator=gpu \
#     trainer.strategy=ddp \
#     trainer.max_epochs=1000 \
#     trainer.log_every_n_steps=10 \
#     +trainer.check_val_every_n_epoch=10 \
#     exp_manager.checkpoint_callback_params.every_n_epochs=10 \
#     +exp_manager.checkpoint_callback_params.save_last=False \
#     model.train_ds.batch_size=32 \
#     trainer.accumulate_grad_batches=2 \
#     model.train_ds.session_len_sec=110 \
#     model.train_ds.num_workers=10 \
#     model.optim.sched.warmup_steps=2500 \
#     model.optim.sched.min_lr=1e-07 \
#     model.optim.lr=5e-5 \
#     model.sortformer_modules.dropout_rate=0.2 \
#     model.encoder.self_attention_model=no_pos_emb \
#     model.validation_ds.batch_size=4 \
#     model.encoder.n_layers=8 \
#     +evaluate_at_start=True \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/tmp/nemo_experiments/dk_nemo_eend_ami_overfit \
#     exp_manager.create_wandb_logger=True \
#     +trainer.gradient_clip_val=1.0 \
#     exp_manager.wandb_logger_kwargs.name=110s_train_110s_valid_noforcefirstactive_noposembeds_8l_1gpu_fixed \
#     exp_manager.wandb_logger_kwargs.project=dk_nemo_eend_ami_overfit \
#     name=110s_train_110s_valid_noforcefirstactive_noposembeds_8l_1gpu_fixed

python /home/jovyan/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_diar_train.py \
    --config-path=/home/jovyan/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
    --config-name=eend_spk_buff.yaml \
    model.train_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_120s_4spks.jsonl \
    model.validation_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_110s.jsonl \
    +model.train_ds.equalize_recording_lengths=True \
    trainer.devices=-1 \
    trainer.accelerator=gpu \
    trainer.strategy=ddp \
    model.max_num_of_spks=4 \
    trainer.max_epochs=1000 \
    trainer.log_every_n_steps=10 \
    +trainer.check_val_every_n_epoch=10 \
    exp_manager.checkpoint_callback_params.every_n_epochs=10 \
    +exp_manager.checkpoint_callback_params.save_last=False \
    model.train_ds.batch_size=32 \
    model.preprocessor.features=23 \
    trainer.accumulate_grad_batches=1 \
    model.train_ds.session_len_sec=120 \
    +model.train_ds.persistent_workers=True \
    +model.validation_ds.persistent_workers=True \
    model.train_ds.num_workers=10 \
    model.optim.sched.warmup_steps=2500 \
    model.optim.sched.min_lr=1e-07 \
    model.optim.lr=3e-5 \
    model.sortformer_modules.dropout_rate=0.2 \
    model.validation_ds.batch_size=1 \
    model.encoder.n_layers=4 \
    model.model_defaults.d_model=256 \
    model.encoder.self_attention_model=no_pos_emb \
    +evaluate_at_start=False \
    +init_from_nest=False \
    exp_manager.resume_ignore_no_checkpoint=True \
    exp_manager.exp_dir=/tmp/nemo_experiments/dk_nemo_eend_ami_overfit \
    exp_manager.create_wandb_logger=True \
    +trainer.gradient_clip_val=0 \
    model.optim.weight_decay=0 \
    exp_manager.wandb_logger_kwargs.name=4l_256d_pil_compound_lr_3e-5_wd_0_warmup_5k_nogradclip_10spks_0.0_dp_fullattn_120s_4spks_23lmel \
    exp_manager.wandb_logger_kwargs.project=dk_nemo_eend_ami_overfit \
    name=4l_256d_pil_compound_lr_3e-5_wd_0_warmup_5k_nogradclip_10spks_0.0_dp_fullattn_120s_4spks_23lmel

# python /home/jovyan/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_diar_train.py \
#     --config-path=/home/jovyan/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
#     --config-name=eend_pil_loss_4spk.yaml \
#     model.train_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_110s.jsonl \
#     model.validation_ds.manifest_filepath=/home/jovyan/data/diar_data/compound_jiangyu_dataset/data_ssd/dev/ami_only_nemo_manifest_110s.jsonl \
#     +model.train_ds.equalize_recording_lengths=True \
#     trainer.devices=-1 \
#     trainer.accelerator=gpu \
#     trainer.strategy=auto \
#     trainer.max_epochs=1000 \
#     trainer.log_every_n_steps=10 \
#     +trainer.check_val_every_n_epoch=1 \
#     exp_manager.checkpoint_callback_params.every_n_epochs=10 \
#     +exp_manager.checkpoint_callback_params.save_last=False \
#     model.train_ds.batch_size=32 \
#     trainer.accumulate_grad_batches=2 \
#     model.train_ds.session_len_sec=110 \
#     model.train_ds.num_workers=10 \
#     model.optim.sched.warmup_steps=2500 \
#     model.optim.sched.min_lr=1e-07 \
#     model.optim.lr=5e-5 \
#     model.sortformer_modules.dropout_rate=0.2 \
#     model.encoder.self_attention_model=no_pos_emb \
#     model.validation_ds.batch_size=16 \
#     model.validation_ds.num_workers=10 \
#     model.validation_ds.prefetch_factor=1 \
#     model.validation_ds.session_len_sec=110 \
#     model.encoder.n_layers=8 \
#     +evaluate_at_start=True \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/tmp/nemo_experiments/dk_nemo_eend_ami_overfit \
#     exp_manager.create_wandb_logger=False \
#     +trainer.gradient_clip_val=1.0 \
#     exp_manager.wandb_logger_kwargs.name=110s_train_110s_valid_noforcefirstactive_noposembeds_8l_1gpu_v3 \
#     exp_manager.wandb_logger_kwargs.project=dk_nemo_eend_ami_overfit \
#     name=110s_train_110s_valid_noforcefirstactive_noposembeds_8l_1gpu_v3
