#!/bin/bash

validation_manifest=$1
model_checkpoint=$2
exp_dir=$3

python /home/jovyan/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_spk_buffer_diar_train.py \
    --config-path=/home/jovyan/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
    --config-name=eend_spk_buff.yaml \
    model.train_ds.manifest_filepath=/mnt/scratch/tmp/xkleme15/compound_jiangyu_dataset/data_ssd/train/nemo_manifest_16s_4spk.jsonl \
    model.validation_ds.manifest_filepath=$validation_manifest \
    +model.train_ds.equalize_recording_lengths=False \
    trainer.devices=-1 \
    trainer.accelerator=gpu \
    trainer.strategy=ddp \
    +model.use_powerset_loss=true \
    model.optim.weight_decay=0.001 \
    model.max_num_of_spks=4 \
    +model.max_overlapping_speakers=2 \
    trainer.max_epochs=1000 \
    trainer.log_every_n_steps=10 \
    trainer.val_check_interval=0.5 \
    model.train_ds.batch_size=64 \
    model.validation_ds.batch_size=128 \
    trainer.accumulate_grad_batches=1 \
    model.train_ds.session_len_sec=16 \
    model.validation_ds.session_len_sec=16 \
    model.train_ds.num_workers=10 \
    model.optim.lr=1e-5 \
    model.optim.sched.min_lr=1e-7 \
    model.model_defaults.d_model=512 \
    +model.encoder.prepend_global_tokens=false \
    +model.use_transformer_attractors=false \
    +model.attr_loss_weight=0.1 \
    +model.powerset_logit_dropout=0.1 \
    +model.encoder.spk_buffer_size=32 \
    +model.encoder.use_ce_spk_buffer=false \
    +model.encoder.use_ce_spk_buffer_bias=true \
    model.sortformer_modules.dropout_rate=0.5 \
    +model.ta_weights_init_constant=1.0 \
    +model.use_scaled_cos_sim_for_attr_dot=false \
    +model.attr_dot_scale_lr_multiplier=10 \
    +model.learnable_vectors_lr_multiplier=1 \
    +model.detach_attr_exist_loss=False \
    +model.attr_dot_scale_init_val=10.0 \
    +model.ta_dropout_att=0.1 \
    +model.ta_attr_dropout=0.1 \
    model.encoder.n_layers=18 \
    model.encoder.att_context_size=[-1,-1] \
    model.encoder.self_attention_model=rel_pos \
    model.encoder.att_context_style=regular \
    +model.encoder.global_tokens=0 \
    +model.encoder.global_tokens_spacing=1 \
    +model.encoder.global_attn_separate=false \
    model.optim.sched.warmup_steps=25000 \
    +decode_only=True \
    exp_manager.resume_ignore_no_checkpoint=True \
    exp_manager.exp_dir=$exp_dir \
    exp_manager.create_wandb_logger=False \
    +model.save_predictions=True \
    +load_everything_from_ptl_ckpt=$model_checkpoint \
