#!/bin/bash

# export WANDB_API_KEY="029a7cc91a821854880a156d05653e9b79d9e7d6"
export WANDB_MODE="online"

# manifest_path="/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/manifests"
manifest_path="/tmp/dicow_data/nemo_manifests"

export PYTHONDONTWRITEBYTECODE=false
export HYDRA_FULL_ERROR=1

# export CUDA_LAUNCH_BLOCKING=1
# export NCCL_DEBUG=INFO
# export PYTHONFAULTHANDLER=1
export OMP_NUM_THREADS=8
export CUDA_VISIBLE_DEVICE=0,1,2,3

# python /storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_diar_train.py \
#     --config-path=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
#     --config-name=eend_pil_loss_4spk.yaml \
#     model.train_ds.manifest_filepath=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/diar_data/data_ssd/dev/ami_only_nemo_manifest_110s.jsonl \
#     model.validation_ds.manifest_filepath=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/diar_data/data_ssd/dev/ami_only_nemo_manifest_110s.jsonl \
#     +model.train_ds.equalize_recording_lengths=True \
#     trainer.devices=-1 \
#     trainer.accelerator=gpu \
#     trainer.strategy=ddp \
#     trainer.max_epochs=1000 \
#     trainer.log_every_n_steps=10 \
#     +trainer.check_val_every_n_epoch=10 \
#     exp_manager.checkpoint_callback_params.every_n_epochs=10 \
#     +exp_manager.checkpoint_callback_params.save_last=False \
#     model.train_ds.batch_size=16 \
#     trainer.accumulate_grad_batches=1 \
#     model.train_ds.session_len_sec=110 \
#     model.train_ds.num_workers=10 \
#     model.optim.sched.warmup_steps=2500 \
#     model.optim.sched.min_lr=1e-07 \
#     model.optim.lr=5e-5 \
#     model.sortformer_modules.dropout_rate=0.2 \
#     model.validation_ds.batch_size=4 \
#     model.encoder.n_layers=8 \
#     model.encoder.att_context_size=[128,128] \
#     model.encoder.self_attention_model=rel_pos_local_attn \
#     model.encoder.att_context_style=regular \
#     +model.encoder.global_tokens=4 \
#     +model.encoder.global_tokens_spacing=1 \
#     +model.encoder.global_attn_separate=false \
#     +evaluate_at_start=True \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/scratch.ssd/dklement/job_11306482.pbs-m1/nemo_experiments/dk_nemo_eend_ami_overfit \
#     exp_manager.create_wandb_logger=True \
#     +trainer.gradient_clip_val=1.0 \
#     exp_manager.wandb_logger_kwargs.name=110s_train_110s_valid_noforcefirstactive_rel_local_attn_4_global \
#     exp_manager.wandb_logger_kwargs.project=dk_nemo_eend_ami_overfit \
#     name=110s_train_110s_valid_noforcefirstactive_rel_local_attn_4_global

# python /storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_diar_train.py \
#     --config-path=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
#     --config-name=eend_pil_loss_4spk.yaml \
#     model.train_ds.manifest_filepath=/scratch.ssd/dklement/job_11306482.pbs-m1/diar_data/sim_librispeech_3k_120s_correct/manifests/sim-librispeech-train-nemo.jsonl \
#     model.validation_ds.manifest_filepath=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/diar_data/data_ssd/dev/ami_only_nemo_manifest_300s.jsonl \
#     +model.train_ds.equalize_recording_lengths=True \
#     trainer.devices=-1 \
#     trainer.accelerator=gpu \
#     trainer.strategy=ddp \
#     trainer.max_epochs=1000 \
#     trainer.log_every_n_steps=10 \
#     +trainer.check_val_every_n_epoch=1 \
#     model.train_ds.batch_size=16 \
#     trainer.accumulate_grad_batches=1 \
#     model.train_ds.session_len_sec=110 \
#     model.train_ds.num_workers=10 \
#     model.optim.sched.warmup_steps=5000 \
#     model.optim.sched.min_lr=1e-07 \
#     model.optim.lr=5e-5 \
#     model.sortformer_modules.dropout_rate=0.2 \
#     model.validation_ds.batch_size=4 \
#     model.encoder.n_layers=8 \
#     model.encoder.att_context_size=[128,128] \
#     model.encoder.self_attention_model=rel_pos_local_attn \
#     model.encoder.att_context_style=regular \
#     +model.encoder.global_tokens=1 \
#     +model.encoder.global_tokens_spacing=1 \
#     +model.encoder.global_attn_separate=false \
#     model.optim.sched.warmup_steps=5000 \
#     model.optim.sched.min_lr=1e-07 \
#     model.optim.lr=5e-5 \
#     model.sortformer_modules.dropout_rate=0.2 \
#     model.validation_ds.batch_size=1 \
#     +init_from_nest=False \
#     +evaluate_at_start=True \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/scratch.ssd/dklement/job_11306482.pbs-m1/nemo_experiments \
#     exp_manager.create_wandb_logger=True \
#     +trainer.gradient_clip_val=1.0 \
#     exp_manager.wandb_logger_kwargs.name=fastconformer_eend_8l_pil_ls-sim_3k_hr_110s_lr_5e-5_warmup_2.5k_gradclip_1_10spks_0.2_dp_local_attn_1_global_v2 \
#     exp_manager.wandb_logger_kwargs.project=dk_nemo_tests \
#     name=fastconformer_eend_8l_pil_ls-sim_3k_hr_110s_lr_5e-5_warmup_2.5k_gradclip_1_10spks_0.2_dp_local_attn_1_global_v2

# python /storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_diar_train.py \
#     --config-path=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
#     --config-name=eend_pil_loss_4spk.yaml \
#     model.train_ds.manifest_filepath=/scratch.ssd/dklement/job_11306482.pbs-m1/diar_data/sim_emilia_3k_hours_100k_meetings_120s/manifests/sim-emilia-train-nemo.jsonl \
#     model.validation_ds.manifest_filepath=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/diar_data/data_ssd/dev/ami_only_nemo_manifest_300s.jsonl \
#     +model.train_ds.equalize_recording_lengths=True \
#     trainer.devices=-1 \
#     trainer.accelerator=gpu \
#     trainer.strategy=ddp \
#     trainer.max_epochs=1000 \
#     trainer.log_every_n_steps=10 \
#     +trainer.check_val_every_n_epoch=1 \
#     model.train_ds.batch_size=16 \
#     trainer.accumulate_grad_batches=1 \
#     model.train_ds.session_len_sec=110 \
#     model.train_ds.num_workers=12 \
#     model.optim.sched.warmup_steps=5000 \
#     model.optim.sched.min_lr=1e-07 \
#     model.optim.lr=5e-5 \
#     model.sortformer_modules.dropout_rate=0.2 \
#     model.validation_ds.batch_size=4 \
#     model.encoder.n_layers=8 \
#     model.encoder.att_context_size=[128,128] \
#     model.encoder.self_attention_model=rel_pos_local_attn \
#     model.encoder.att_context_style=regular \
#     +model.encoder.global_tokens=1 \
#     +model.encoder.global_tokens_spacing=1 \
#     +model.encoder.global_attn_separate=false \
#     model.optim.sched.warmup_steps=5000 \
#     model.optim.sched.min_lr=1e-07 \
#     model.optim.lr=5e-5 \
#     model.sortformer_modules.dropout_rate=0.2 \
#     model.validation_ds.batch_size=1 \
#     +init_from_nest=False \
#     +evaluate_at_start=True \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/scratch.ssd/dklement/job_11306482.pbs-m1/nemo_experiments \
#     exp_manager.create_wandb_logger=True \
#     +trainer.gradient_clip_val=1.0 \
#     exp_manager.wandb_logger_kwargs.name=fastconformer_eend_8l_pil_emilia-sim_3k_hr_110s_lr_5e-5_warmup_2.5k_gradclip_1_10spks_0.2_dp_local_attn_1_global_v2 \
#     exp_manager.wandb_logger_kwargs.project=dk_nemo_tests \
#     name=fastconformer_eend_8l_pil_emilia-sim_3k_hr_110s_lr_5e-5_warmup_2.5k_gradclip_1_10spks_0.2_dp_local_attn_1_global_v2

python /storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/speaker_tasks/diarization/neural_diarizer/eend_diar_train.py \
    --config-path=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/examples/speaker_tasks/diarization/conf/neural_diarizer \
    --config-name=eend_pil_loss_4spk.yaml \
    model.train_ds.manifest_filepath=/scratch.ssd/dklement/job_11306482.pbs-m1/diar_data/sim_emilia_12k_hours_200k_meetings_240s/manifests/sim-emilia-train-nemo.jsonl \
    model.validation_ds.manifest_filepath=/storage/brno12-cerit/home/dklement/speech/ASR/NeMo/misc/diar_data/data_ssd/dev/ami_only_nemo_manifest_300s.jsonl \
    +model.train_ds.equalize_recording_lengths=True \
    trainer.devices=-1 \
    trainer.accelerator=gpu \
    trainer.strategy=ddp \
    trainer.max_epochs=1000 \
    trainer.log_every_n_steps=10 \
    +trainer.check_val_every_n_epoch=1 \
    model.train_ds.batch_size=16 \
    trainer.accumulate_grad_batches=1 \
    model.train_ds.session_len_sec=240 \
    model.train_ds.num_workers=12 \
    model.optim.sched.warmup_steps=5000 \
    model.optim.sched.min_lr=1e-07 \
    model.optim.lr=5e-5 \
    model.sortformer_modules.dropout_rate=0.2 \
    model.validation_ds.batch_size=4 \
    model.encoder.n_layers=8 \
    model.encoder.att_context_size=[128,128] \
    model.encoder.self_attention_model=rel_pos_local_attn \
    model.encoder.att_context_style=regular \
    +model.encoder.global_tokens=1 \
    +model.encoder.global_tokens_spacing=1 \
    +model.encoder.global_attn_separate=false \
    model.optim.sched.warmup_steps=5000 \
    model.optim.sched.min_lr=1e-07 \
    model.optim.lr=5e-5 \
    model.sortformer_modules.dropout_rate=0.2 \
    model.validation_ds.batch_size=1 \
    +init_from_nest=False \
    +evaluate_at_start=True \
    exp_manager.resume_ignore_no_checkpoint=True \
    exp_manager.exp_dir=/scratch.ssd/dklement/job_11306482.pbs-m1/nemo_experiments \
    exp_manager.create_wandb_logger=True \
    +trainer.gradient_clip_val=1.0 \
    exp_manager.wandb_logger_kwargs.name=fastconformer_eend_8l_pil_emilia-sim_12k_hr_240s_lr_5e-5_warmup_2.5k_gradclip_1_10spks_0.2_dp_local_attn_1_global \
    exp_manager.wandb_logger_kwargs.project=dk_nemo_tests \
    name=fastconformer_eend_8l_pil_emilia-sim_12k_hr_240s_lr_5e-5_warmup_2.5k_gradclip_1_10spks_0.2_dp_local_attn_1_global
