#!/bin/bash

# export WANDB_API_KEY="029a7cc91a821854880a156d05653e9b79d9e7d6"
export WANDB_MODE="online"



# python ~/NeMo/examples/asr/ts_asr_ctc/speech_to_text_ctc_bpe.py \
#     --config-path="/home/jovyan/NeMo/examples/asr/conf/fastconformer" \
#     --config-name="fast-conformer_ctc_bpe_stno.yaml" \
#     model.train_ds.manifest_filepath=/tmp/nsf_nemo_train_sc_30s.jsonl \
#     model.validation_ds.manifest_filepath=/tmp/nsf_nemo_train_sc_30s.jsonl \
#     model.tokenizer.dir=/home/jovyan/NeMo/tokenizers/ls960/tokenizer_spe_bpe_v500 \
#     model.tokenizer.type="bpe" \
#     trainer.devices=-1 \
#     trainer.accelerator="gpu" \
#     trainer.strategy="ddp" \
#     trainer.max_epochs=1200 \
#     model.encoder.d_model=256 \
#     model.encoder.n_heads=4 \
#     model.encoder.n_layers=16 \
#     model.encoder.conv_kernel_size=9 \
#     model.optim.weight_decay=1e-3 \
#     model.optim.lr=7e-4 \
#     trainer.log_every_n_steps=20 \
#     trainer.check_val_every_n_epoch=4 \
#     model.train_ds.batch_size=128 \
#     model.validation_ds.batch_size=128 \
#     exp_manager.resume_if_exists=True \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir="/home/jovyan/NeMo/nemo_experiments" \
#     exp_manager.create_wandb_logger=True \
#     exp_manager.wandb_logger_kwargs.name="fastconformer_ctc_bpe_stno_nsf_test_v12" \
#     exp_manager.wandb_logger_kwargs.project="nemo_tests" \
#     exp_manager.checkpoint_callback_params.monitor="val/cp_wer" \
#     name="FastConformer-CTC-BPE-cpwer_scoring" \
#     +model.decoding.compute_timestamps=True \
#     +model.decoding.strategy=greedy

# python ~/NeMo/examples/asr/ts_asr_ctc/speech_to_text_ctc_bpe.py \
#     --config-path="/home/jovyan/NeMo/examples/asr/conf/fastconformer" \
#     --config-name="fast-conformer_ctc_bpe_stno_parakeet_0.6b.yaml" \
#     model.train_ds.manifest_filepath=/tmp/dicow_data/nemo_manifests/ami_nsf_l2m_both_100_360_compound_trainset.jsonl \
#     model.validation_ds.manifest_filepath=/tmp/dicow_data/nemo_manifests/notsofar_eval_sc_cutset.jsonl \
#     model.tokenizer.dir=/tmp/tokenizers/ls960/tokenizer_spe_bpe_v500 \
#     model.tokenizer.type=bpe \
#     trainer.devices=-1 \
#     trainer.accelerator=gpu \
#     trainer.strategy=ddp \
#     +evaluate_at_start=true \
#     trainer.max_epochs=100 \
#     model.fddt_lr_multiplier=100 \
#     trainer.log_every_n_steps=10 \
#     model.train_ds.batch_size=32 \
#     model.optim.sched.warmup_steps=2000 \
#     model.optim.lr=5e-4 \
#     trainer.accumulate_grad_batches=2 \
#     model.validation_ds.batch_size=1 \
#     exp_manager.resume_if_exists=True \
#     exp_manager.resume_ignore_no_checkpoint=True \
#     exp_manager.exp_dir=/tmp/nemo_experiments \
#     exp_manager.checkpoint_callback_params.monitor=val/cp_wer \
#     exp_manager.create_wandb_logger=True \
#     exp_manager.wandb_logger_kwargs.name=parakeet_ctc_0.6b_fddt_lr_mul_100_lr5e-4_ami_nsf_l2m_30s_nsf_dev_longform_2k_warmup_64bs \
#     exp_manager.wandb_logger_kwargs.project=dk_nemo_tests \
#     +init_from_pretrained=nvidia/parakeet-ctc-0.6b \
#     name=parakeet_ctc_0.6b_fddt_lr_mul_100_lr5e-4_ami_nsf_l2m_30s_nsf_dev_longform_2k_warmup_64bs \
#     +model.decoding.compute_timestamps=True \
#     +model.decoding.preserve_alignments=True

python ~/NeMo/examples/asr/ts_asr_ctc/speech_to_text_ctc_bpe.py \
    --config-path="/home/jovyan/NeMo/examples/asr/conf/fastconformer" \
    --config-name="fast-conformer_ctc_bpe_stno_parakeet_110m.yaml" \
    model.train_ds.manifest_filepath=/tmp/dicow_data/nemo_manifests/ami_nsf_l2m_both_100_360_compound_trainset.jsonl \
    model.validation_ds.manifest_filepath=/tmp/dicow_data/nemo_manifests/notsofar_eval_sc_cutset.jsonl \
    model.tokenizer.dir=/tmp/tokenizers/ls960/tokenizer_spe_bpe_v500 \
    model.tokenizer.type=bpe \
    trainer.devices=-1 \
    trainer.accelerator=gpu \
    trainer.strategy=ddp \
    +evaluate_at_start=true \
    trainer.max_epochs=100 \
    model.fddt_lr_multiplier=100 \
    trainer.log_every_n_steps=10 \
    model.train_ds.batch_size=32 \
    model.optim.sched.warmup_steps=2000 \
    model.optim.lr=1e-4 \
    trainer.accumulate_grad_batches=2 \
    model.validation_ds.batch_size=1 \
    exp_manager.resume_if_exists=True \
    exp_manager.resume_ignore_no_checkpoint=True \
    exp_manager.exp_dir=/tmp/nemo_experiments \
    exp_manager.checkpoint_callback_params.monitor=val/cp_wer \
    exp_manager.create_wandb_logger=True \
    exp_manager.wandb_logger_kwargs.name=parakeet_ctc_110m_fddt_lr_mul_100_lr1e-4_ami_nsf_l2m_30s_nsf_dev_longform_2k_warmup_128bs_fixed_lrmul \
    exp_manager.wandb_logger_kwargs.project=dk_nemo_tests \
    +init_from_pretrained=nvidia/parakeet-tdt_ctc-110m \
    name=parakeet_110m_ctconly_fddt_lr_mul_100_lr1e-4_ami_nsf_l2m_30s_nsf_dev_longform_2k_warmup_128bs_fixed_lrmul \
    +model.decoding.compute_timestamps=True \
    +model.decoding.preserve_alignments=True

# python examples/asr/asr_ctc/speech_to_text_ctc_bpe.py \
#     --config-path="/home/jovyan/NeMo/examples/asr/conf/fastconformer" \
#     --config-name="fast-conformer_ctc_bpe.yaml" \
#     model.train_ds.manifest_filepath=/tmp/librispeech/lhotse_manifests/librispeech_cuts_train-other-500.jsonl.gz \
#     model.validation_ds.manifest_filepath=/tmp/librispeech/lhotse_manifests/librispeech_cuts_dev-other.jsonl.gz \
#     model.tokenizer.dir=/tmp/librispeech/tokenizer_spe_bpe_v500 \
#     model.tokenizer.type="bpe" \
#     trainer.devices=-1 \
#     trainer.accelerator="gpu" \
#     trainer.strategy="ddp" \
#     trainer.max_epochs=100 \
#     model.encoder.d_model=176 \
#     model.encoder.n_heads=8 \
#     model.encoder.n_layers=16 \
#     model.encoder.conv_kernel_size=9 \
#     model.optim.weight_decay=0.0 \
#     model.train_ds.batch_size=256 \
#     model.validation_ds.batch_size=32 \
#     exp_manager.create_wandb_logger=True \
#     ++model.train_ds.use_lhotse=True \
#     ++model.validation_ds.use_lhotse=True \
#     ++model.train_ds.batch_duration=1100 \
#     ++model.train_ds.quadratic_duration=30 \
#     ++model.train_ds.num_buckets=30 \
#     ++model.train_ds.num_cuts_for_bins_estimate=10000 \
#     ++model.train_ds.bucket_buffer_size=10000 \
#     ++model.train_ds.shuffle_buffer_size=10000 \  
#     ++trainer.use_distributed_sampler=false \
#     ++trainer.limit_train_batches=1000 \
#     exp_manager.wandb_logger_kwargs.name="fastconformer_ctc_500bpe_ls960_small_honza_256bs_v2_lhotse" \
#     exp_manager.wandb_logger_kwargs.project="nemo_tests" \
